import type { Metadata } from "next";
import { StructuredData } from "@/components/structured-data";
import { RelatedTools } from "@/components/related-tools";
import { toolStructuredData } from "@/lib/seo";
import { RentalComparisonCalculator } from "@/components/calculators/rental-comparison";
import { pageMetadata, siteConfig } from "@/lib/site-config";
const title = "Alugar carro ou usar aplicativo na viagem?";
const description = "Compare o custo de um veículo alugado com transporte por aplicativo considerando locação, combustível, estacionamento, pedágios, corridas e tempo de espera.";
export const metadata: Metadata = pageMetadata(title, description, "/veiculo-alugado-ou-aplicativo/");
export default function RentalComparisonPage() {
  return <div className="container calculator-page"><StructuredData data={toolStructuredData(title, description, "/veiculo-alugado-ou-aplicativo/")} /><a href="/#viagens" className="text-link">← Voltar para viagens</a><header className="calculator-heading"><p className="eyebrow">Preço não é necessariamente custo</p><h1>Veículo alugado ou aplicativo?</h1><p>Compare o custo de alugar um veículo com o uso de aplicativos durante a sua viagem.</p></header><RentalComparisonCalculator reportBrand={{ name: siteConfig.name, domain: siteConfig.reportDomain }} /><section className="calculator-guide"><h2>Como interpretar a comparação</h2><div><h3>Quanto custa a mobilidade da viagem?</h3><p>Para avaliar alugar um carro ou usar transporte por aplicativo, considere os gastos de toda a viagem. A locação pode ter combustível, estacionamento, pedágios e despesas de devolução além da cotação inicial. Cada corrida prevista também contribui para o total do aplicativo.</p></div><div><h3>Dias da viagem e diárias da locação</h3><p>Informe separadamente os dias que deseja comparar e as diárias de aluguel. Você pode precisar do veículo em apenas parte da viagem. Pessoas são opcionais e servem para uma divisão simples do custo; não multiplicam os gastos.</p></div><div><h3>Estimativas informadas por você</h3><p>Consulte sua cotação e simule as corridas no aplicativo para ter referências, sem solicitar transporte. Ida e volta podem ter preços e esperas diferentes. A ferramenta não busca preços, rotas ou disponibilidade e não aplica multiplicadores de tarifa.</p></div><div><h3>Espera e caução separadas do dinheiro gasto</h3><p>O tempo informado mostra apenas a espera por motoristas, sem duração dos trajetos nem valor monetário. A caução é apresentada separadamente como limite temporariamente comprometido. A comparação descreve os custos; conforto e preferências pessoais ficam a seu critério.</p></div><p>Os resultados são estimativas baseadas exclusivamente nos valores informados, com caráter informativo, e não constituem recomendação financeira.</p></section><RelatedTools current="/veiculo-alugado-ou-aplicativo/" /></div>;
}
