import type { Metadata } from "next";
import { StructuredData } from "@/components/structured-data";
import { RelatedTools } from "@/components/related-tools";
import { toolStructuredData } from "@/lib/seo";
import { LodgingComparisonCalculator } from "@/components/calculators/lodging-comparison";
import { pageMetadata, siteConfig } from "@/lib/site-config";
const title = "Comparador de hospedagens: preço e custo total";
const description = "Compare o custo real de duas hospedagens considerando preço, refeições, estacionamento, transporte e tempo de deslocamento durante a viagem.";
export const metadata: Metadata = pageMetadata(title, description, "/comparar-hospedagens/");
export default function LodgingComparisonPage() {
  return <div className="container calculator-page"><StructuredData data={toolStructuredData(title, description, "/comparar-hospedagens/")} /><a href="/#viagens" className="text-link">← Voltar para viagens</a><header className="calculator-heading"><p className="eyebrow">Preço não é necessariamente custo</p><h1>Comparar hospedagens</h1><p>Descubra qual hospedagem realmente custa menos durante a sua viagem.</p></header><LodgingComparisonCalculator reportBrand={{ name: siteConfig.name, domain: siteConfig.reportDomain }} /><section className="calculator-guide"><h2>Como interpretar a comparação</h2><div><h3>Preço da reserva × custo comparável</h3><p>A reserva mais barata pode gerar gastos adicionais de alimentação, estacionamento e deslocamento. Compare o preço da hospedagem com o total informado para entender o que muda entre as opções. A ferramenta não calcula todo o orçamento da viagem.</p></div><div><h3>A mesma viagem, duas localizações</h3><p>Cadastre os locais que pretende visitar uma única vez. Para cada hospedagem, informe distâncias, custos e tempos. Uma visita inclui os trechos escolhidos: ida e volta, somente ida ou somente volta. Para carro próprio ou alugado, entram apenas os gastos de deslocamento, sem custos fixos do veículo.</p></div><div><h3>Compare apenas o que muda</h3><p>Você pode omitir gastos que seriam iguais nas duas hospedagens. Refeições usam estimativas por pessoa e dias informados; estacionamento e transporte representam o grupo inteiro. Distâncias, preços e tempos são informados por você, sem busca de hotéis, tarifas ou rotas.</p></div><div><h3>Tempo e dinheiro separados</h3><p>O tempo não recebe valor monetário e não inclui espera por aplicativo. A comparação é informativa: qualidade, segurança, disponibilidade e preferências pessoais também podem participar da sua decisão, mas não são avaliadas aqui.</p></div></section><RelatedTools current="/comparar-hospedagens/" /></div>;
}
