import type { Metadata } from "next";
import { StructuredData } from "@/components/structured-data";
import { RelatedTools } from "@/components/related-tools";
import { toolStructuredData } from "@/lib/seo";
import { MealComparisonCalculator } from "@/components/calculators/meal-comparison";
import { pageMetadata, siteConfig } from "@/lib/site-config";
const title = "Comer fora ou cozinhar? Compare os custos";
const description = "Compare quanto custa preparar suas refeições em casa e comer fora, veja o impacto mensal e descubra quais refeições fazem mais diferença no seu orçamento.";
export const metadata: Metadata = pageMetadata(title, description, "/comer-fora-ou-cozinhar/");
export default function MealComparisonPage() {
  return <div className="container calculator-page"><StructuredData data={toolStructuredData(title, description, "/comer-fora-ou-cozinhar/")} /><a href="/" className="text-link">← Voltar ao início</a><header className="calculator-heading"><p className="eyebrow">Sua alimentação, em números</p><h1>Comer fora<br /><span>ou cozinhar?</span></h1><p>Descubra qual vale mais a pena na sua rotina.</p></header><MealComparisonCalculator reportBrand={{ name: siteConfig.name, domain: siteConfig.reportDomain }} /><section className="calculator-guide"><h2>Como comparar sua rotina de alimentação</h2><div><h3>Comece pelas refeições que fazem parte do seu dia</h3><p>Compare café da manhã, almoço, lanche, jantar ou uma refeição personalizada. Os ingredientes ajudam a calcular o custo de preparar uma refeição; a comparação principal é entre refeições, com os preços que você informar.</p></div><div><h3>Da compra ao custo por refeição</h3><p>Informe a quantidade utilizada, o preço da compra e quanto veio nela. Massa pode ser informada em g ou kg, volume em ml ou L, e itens contados em unidades. A frequência semanal transforma os custos por refeição em estimativas mensais e anuais.</p></div><div><h3>Custos de preparo e tempo são opcionais</h3><p>Inclua somente gás, energia ou outros gastos que existem ou aumentam por causa do preparo. Esses valores aparecem separados dos alimentos. Compras, preparo, limpeza e o tempo para comer fora podem ser informados em horas semanais; tempo não é convertido em dinheiro.</p></div><div><h3>Interprete com os seus valores</h3><p>Cozinhar ou comprar comida pode custar mais ou menos conforme sua rotina. A ferramenta não usa preços de mercado, não indica alimentos ou receitas e não avalia aspectos nutricionais. Refeições com campos essenciais incompletos ficam fora dos totais até serem preenchidas. Zero informado é preservado. Compare os números e decida como interpretá-los.</p></div></section><RelatedTools current="/comer-fora-ou-cozinhar/" /></div>;
}
