import type { Metadata } from "next";
import { StructuredData } from "@/components/structured-data";
import { RelatedTools } from "@/components/related-tools";
import { toolStructuredData } from "@/lib/seo";
import { PropertyComparisonCalculator } from "@/components/calculators/property-comparison";
import { pageMetadata, siteConfig } from "@/lib/site-config";
const title = "Comparar imóveis: custo total de moradia";
const description = "Compare dois imóveis considerando aluguel ou parcela, condomínio, itens incluídos e impactos da localização. Veja custos e tempo separados, sem cadastro.";
export const metadata: Metadata = pageMetadata(title, description, "/comparar-imoveis/");
export default function PropertyComparisonPage() {
  return <div className="container calculator-page"><StructuredData data={toolStructuredData(title, description, "/comparar-imoveis/")} /><a href="/" className="text-link">← Voltar ao início</a><header className="calculator-heading"><p className="eyebrow">Preço não é necessariamente custo</p><h1>Comparar imóveis:<br /><span>o que muda na sua rotina?</span></h1><p>O aluguel mais barato realmente custa menos? Compare o custo da moradia, os gastos que mudam com a localização e o tempo de deslocamento. Você decide como interpretar cada diferença.</p></header><PropertyComparisonCalculator reportBrand={{ name: siteConfig.name, domain: siteConfig.reportDomain }} /><section className="calculator-guide"><h2>Como interpretar a comparação</h2><div><h3>O preço é só o começo</h3><p>O custo direto reúne aluguel ou parcela, condomínio, IPTU e outros custos recorrentes do imóvel. O total recorrente acrescenta os gastos informados de garagem, serviços, transporte, alimentação e localização. Custos únicos aparecem separadamente, sem entrar no total mensal ou anual recorrente.</p></div><div><h3>Compare o que muda</h3><p>Não é preciso repetir gastos iguais nos dois cenários. O checklist ajuda a lembrar diferenças, mas serviços disponíveis não geram economia automaticamente. Você informa se haveria um gasto, qual seria o valor e se ele seria mensal, anual ou uma única vez.</p></div><div><h3>Morar perto ou longe do trabalho</h3><p>Informe a rotina de cada opção, sem presumir que morar longe custa mais. O tempo usa 52 semanas por ano e aparece separado do dinheiro. A comparação não recomenda um imóvel e não calcula financiamento, rotas, reajustes ou custos iniciais de aquisição e mudança.</p></div></section><RelatedTools current="/comparar-imoveis/" /></div>;
}
