import type { Metadata } from "next";
import { PropertyComparisonCalculator } from "@/components/calculators/property-comparison";
import { defaultOpenGraph, siteConfig } from "@/lib/site-config";
const title = "Comparador de imóveis: compare o custo real de duas opções";
const description = "Compare dois imóveis considerando aluguel ou parcela, condomínio, itens incluídos e impactos da localização. Veja custos e tempo separados, sem cadastro.";
export const metadata: Metadata = { title, description, alternates: { canonical: "/comparar-imoveis/" }, openGraph: { ...defaultOpenGraph, title, description, url: "/comparar-imoveis/" } };
export default function PropertyComparisonPage() {
  return <div className="container calculator-page"><a href="/" className="text-link">← Voltar ao início</a><header className="calculator-heading"><p className="eyebrow">Preço não é necessariamente custo</p><h1>Comparar imóveis:<br /><span>o que muda na sua rotina?</span></h1><p>O aluguel mais barato realmente custa menos? Compare o custo da moradia, os gastos que mudam com a localização e o tempo de deslocamento. Você decide como interpretar cada diferença.</p></header><PropertyComparisonCalculator reportBrand={{ name: siteConfig.name, domain: siteConfig.reportDomain }} /><section className="calculator-guide"><h2>Como interpretar a comparação</h2><div><h3>O preço é só o começo</h3><p>O custo direto reúne aluguel ou parcela, condomínio, IPTU, garagem e outros custos do imóvel. O total acrescenta os impactos informados de serviços, transporte, alimentação e localização.</p></div><div><h3>Compare o que muda</h3><p>Não é preciso repetir gastos iguais nos dois cenários. O checklist ajuda a lembrar diferenças, mas serviços disponíveis não geram economia automaticamente. Você informa se haveria um gasto e qual seria o valor.</p></div><div><h3>Morar perto ou longe do trabalho</h3><p>Informe a rotina de cada opção, sem presumir que morar longe custa mais. O tempo usa 52 semanas por ano e aparece separado do dinheiro. A comparação não recomenda um imóvel e não calcula financiamento, rotas, reajustes ou custos iniciais de aquisição e mudança.</p></div><a className="text-link" href="/calculadora-custo-de-vida/">Planejar também meu custo de vida →</a></section></div>;
}
