import type { Metadata } from "next";
import { StructuredData } from "@/components/structured-data";
import { RelatedTools } from "@/components/related-tools";
import { toolStructuredData } from "@/lib/seo";
import { TripCostCalculator } from "@/components/calculators/trip-cost";
import { pageMetadata, siteConfig } from "@/lib/site-config";
const title = "Calculadora de gastos de viagem grátis";
const description = "Calcule o custo estimado da sua viagem com passagens, hospedagem, alimentação, transporte e passeios. Compare destinos e descubra onde estão os maiores gastos.";
export const metadata: Metadata = pageMetadata(title, description, "/custo-da-viagem/");
export default function TripCostPage() {
  return <div className="container calculator-page"><StructuredData data={toolStructuredData(title, description, "/custo-da-viagem/")} /><a href="/#viagens" className="text-link">← Voltar para viagens</a><header className="calculator-heading"><p className="eyebrow">Preço não é necessariamente custo</p><h1>Quanto custa <span>minha viagem?</span></h1><p>Planeje seus gastos, compare destinos e descubra quanto sua viagem pode custar de verdade.</p></header><TripCostCalculator reportBrand={{name:siteConfig.name,domain:siteConfig.reportDomain}} /><section className="calculator-guide"><h2>Como interpretar seu planejamento</h2><div><h3>Olhe além da passagem</h3><p>Hospedagem, alimentação, transporte e passeios podem mudar o custo da viagem. Preencha apenas os gastos que deseja considerar, sem repetir despesas já incluídas em outros valores.</p></div><div><h3>Compare cenários completos</h3><p>Cada destino pode ter sua própria duração e número de viajantes. Compare também o custo por dia e por pessoa. Esses valores não avaliam qualidade, conforto ou preferências, e a ferramenta não recomenda um destino.</p></div><div><h3>Estimativas com transparência</h3><p>Não há busca de preços, integração com companhias aéreas, hotéis ou transporte. Os valores são seus, processados no navegador. Despesas não preenchidas podem alterar o custo final; a reserva para imprevistos representa um valor planejado, não um gasto confirmado.</p></div><div><h3>Use outros resultados manualmente</h3><p>Você pode utilizar os resultados de <a className="text-link" href="/comparar-hospedagens/">Comparar hospedagens</a> e <a className="text-link" href="/veiculo-alugado-ou-aplicativo/">Veículo alugado ou aplicativo?</a>. Registre o total escolhido uma vez, sem duplicar seus componentes. Não há importação automática ou leitura de outras simulações.</p></div></section><RelatedTools current="/custo-da-viagem/" /></div>;
}
